
# spring.profiles.active: jdbc

server.port: 8000

openapi:
  service:
    title: spring-mqtt
    version: 0.0.1
mqtt:
  subscribe:
    url: tcp://localhost:1883
    client-id: spring-mqtt-subscriber
    topic: /pms/#
    qos: 1
    timeout: 10000
    keepAliveInterval: 60
    username: iot
    password: iot
  publish:
    url: tcp://localhost:1883
    client-id: spring-mqtt-publisher
    topic: /pms
    qos: 1
    timeout: 10000
    keepAliveInterval: 60
    username: iot
    password: iot